spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 2000

          #配置某个具体的FeignClient的超时时间
          service-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000


    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true
      #分割web上下文
      web-context-unify: true

  feign:
    sentinel:
      enable: true