server:
  port: 9100

spring:
  profiles:
    include: feign

  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: test
        import-check:
          enabled: false
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev



logging:
  level:
    com.arya.fegin: debug
