server:
  port: 9100

spring:
  profiles:
    include: feign
    active: dev
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        #指定读取配置中心那个命名空间内的配置,这里建议使用命名空间ID，使用名称会抱config is Empty
        namespace: 4c166165-1702-4dc3-bd29-55f25274a91f
        server-addr: 127.0.0.1:8848
        group: order
        file-extension: properties
        refresh-enabled: true


#当配置中心和本地的配置项一样时，以配置中心的配置为准
#配置遵循：外部优先，先导入优先，即配置中心中的配置优先于本地配置，如果配置了的多个DataId中有相同的配置项，则以先导入的为主
#order:
#  timeout: 300min
#  auto-confirm: 70d

logging:
  level:
    com.arya.fegin: debug

---
spring:
  config:
    import:
      #?group=order指定读取那个分组中的配置数据
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev

---
spring:
  config:
    import:
      #?group=order指定读取那个分组中的配置数据
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: test

---
spring:
  config:
    import:
      #?group=order指定读取那个分组中的配置数据
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: prod